##################################################################################################################
## date: 2020/06/05
## author: Áki Jarl Láruson
## Code to visualize expected change in allele frequency based on Wright's formula, 
##  derived from Walsh & Lynch 'Evolution and Selection of Quantitative Traits', chapter 5, equation 5.6e (pg 122)
##################################################################################################################
# Need super user privilages in order to run animation code - right click RStudio and select 'Run as administrator'

packages<-c("ggplot2","dplyr","devtools","gganimate","gifski", "png")

for(j in packages){
  if(!(j %in% installed.packages())){install.packages(j)}
}
lapply(packages,require,character.only = TRUE)

if (!("transformr" %in% installed.packages())){devtools::install_github("thomasp85/transformr")}
require(transformr)


a_i = 0.1 # allele effect size
s = 0.1 # selection coefficient
mu = 0 # mean phenotype
theta = seq(-1,1,0.1) # phenotypic value optimum
p_i=seq(0,1,0.1) # allele frequency

p = tibble(a_i=a_i,p_i=seq(0,1,0.1)) # create allele frequency tibble object to merge

# create a tibble object for use with ggplot
dat<-tibble(a_i = a_i, s = s, mu = mu , theta = theta)
dat<- dat%>%
  full_join(p,by="a_i")

# create a function for equation 5.6e
d_p_i <- function(s, a_i, mu, theta, p_i){
    s*a_i*(p_i*(1-p_i)/2)*(a_i*(2*p_i-1)+2*(theta-mu))
}
# create and fill column in tibble to hold all calculated changes in allele frequency based on eq. 5.6e 
dat$d_p_i <- d_p_i(dat$a_i,dat$s,dat$mu,dat$theta, dat$p_i)

# create a function for equation 5.6f - for comparison, redundant for theta=mu above
d_p_i_2 <- function(s, a_i, p_i){
  s*(a_i^2)*(p_i*(1-p_i))*(p_i-0.5)
}
# create and fill column in tibble to hold all calculated changes in allele frequency based on eq. 5.6f 
dat$d_p_i_2 <- d_p_i_2(dat$a_i,dat$s,dat$p_i)


# visualize the shifts as an animation across different phenotypic values theta
ggplot(aes(x=p_i, y=d_p_i),data=dat)+
  geom_point(size=3)+
  geom_line()+
  geom_hline(yintercept=0, col="red")+
  ylab(expression(paste(Delta, italic(p),": rate of change in allele frequency")))+
  xlab(expression(paste(italic(p)[i],": allele frequency")))+
  theme_classic()+
  transition_time(theta)+
  labs(title = paste("Optimal phenotype = {frame_time}, Mean phenotype = ",mu)) +
  view_follow()


#Looking only at the rate of change in allele frequency when the phentotpye is at the optimum
ggplot()+
  geom_point(aes(x=p_i, y=d_p_i(a_i,s,mu,theta=mu, p_i)), size=3)+
  geom_line(aes(x=p_i, y=d_p_i(a_i,s,mu,theta=mu, p_i)))+
  geom_hline(yintercept=0, col="red")+
  ggtitle(paste("Optimal phenotype = ",mu,", mean phenotype = ",mu))+
  ylab(expression(paste(Delta, italic(p),": rate of change in allele frequency")))+
  xlab(expression(paste(italic(p)[i],": allele frequency")))+
  theme_classic()

#or

ggplot(aes(x=p_i, y=d_p_i_2),data=dat)+
  geom_point(size=3)+
  geom_line()+
  geom_hline(yintercept=0, col="red")+
  ggtitle(paste("Optimal phenotype = ",mu,", mean phenotype = ",mu))+
  ylab(expression(paste(Delta, italic(p),": rate of change in allele frequency")))+
  xlab(expression(paste(italic(p)[i],": allele frequency")))+
  theme_classic()

#the figures generated by the two commands above should be indentical



#Alternative visualization if animation is not working, generates fixed images for all values of theta
for (i in theta){
  print(ggplot()+
          geom_point(aes(x=p_i, y=d_p_i(a_i,s,mu,i, p_i)), size=3)+
          geom_line(aes(x=p_i, y=d_p_i(a_i,s,mu,i, p_i)))+
          #ylim(-0.03,0.03)+
          geom_hline(yintercept=0, col="red")+
          ggtitle(paste("Optimal phenotype = ",i,", mean phenotype = ",mu))+
          ylab(expression(paste(Delta, italic(p),": rate of change in allele frequency")))+
          xlab(expression(paste(italic(p)[i],": allele frequency")))+
          theme_classic()
  )
}


